---
title: "Trabajo Finanzas I"
author: "Melissa, Lucas, Amanda, Exequiel"
date: "2023-03-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Users/oienh/Documents/R_UNIVERSITY_PROJECTS/5th_Semester/trabajo_finanzas")
```

Instrucciones: Elaborar informe de análisis financiero:
Incluir:
- Análisis estático comparativo (últimos dos balances de cierre).
- Análisis de liquidez (ratios).
- Ratios financieros en genreral.
- Ratios económicos (margen, rendimiento, rentabilidad).
- Introducción.
- Marco conceptual.
- Análisis.
- Conclusiones.

Empresa escogida: Amazon

```{r}
library(readxl)

estado_de_resultado <- read_excel("estado_de_resultados.xlsx",  range = "A1:C35")
balance <- read_excel("balance.xlsx",  range = "A1:C35")



total <- "la suma de todo lol"

relativo_porcentual <- apply("", function(x) x / total)

activo_corriente <- sum()
pasivo_corriente <- sum()

capital_trabajo_neto <- activo_corriente - pasivo_corriente
liquidez <- activo_corriente / pasivo_corriente
prueba_acida <- (activo_corriente - inventarios) / pasivo_corriente
liquidez_inmediata <- efectivo y equivalente / pasivo_corriente
solvencia <- pasivos / patrimonio
endeudamiento <- (pasivos - patrimonio) / patrimonio



```

